# Generated by Django 5.2.7 on 2026-03-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_deliveryrequest_current_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddonation',
            name='cooking_time',
            field=models.DateTimeField(blank=True, help_text='When was the food cooked?', null=True),
        ),
    ]
